import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateMissingTables1764699174742 implements MigrationInterface {
    name = 'CreateMissingTables1764699174742'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "fk_orders_table"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "fk_orders_restaurant"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "fk_orders_user"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "fk_order_items_menu_item"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "fk_order_items_order"`);
        await queryRunner.query(`ALTER TABLE "menu_items" DROP CONSTRAINT "fk_menu_items_restaurant"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "fk_reservations_table"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "fk_reservations_restaurant"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "fk_reservations_user"`);
        await queryRunner.query(`ALTER TABLE "restaurants" DROP CONSTRAINT "fk_restaurants_owner"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "fk_user_roles_user"`);
        await queryRunner.query(`ALTER TABLE "tables" DROP CONSTRAINT "fk_tables_restaurant"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "fk_wallet_transactions_wallet"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "fk_wallets_restaurant"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "fk_wallets_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_restaurant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_menu_items_restaurant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reservations_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reservations_restaurant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reservations_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_restaurant_id"`);
        await queryRunner.query(`CREATE TYPE "public"."restaurant_service_configs_service_type_enum" AS ENUM('fine_dining', 'quick_service', 'fast_casual', 'coffee_shop', 'buffet', 'drive_thru', 'food_truck', 'chefs_table')`);
        await queryRunner.query(`CREATE TABLE "restaurant_service_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "restaurant_id" uuid NOT NULL, "service_type" "public"."restaurant_service_configs_service_type_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "sommelier_available" boolean, "dress_code" character varying, "reservation_required" boolean, "average_meal_duration" integer, "skip_the_line_enabled" boolean, "pickup_zones" text, "avg_preparation_time" integer, "build_your_own_enabled" boolean, "customization_options" jsonb, "work_friendly" boolean, "wifi_available" boolean, "power_outlets_available" boolean, "noise_level" character varying, "price_per_kg" numeric(10,2), "fixed_price" numeric(10,2), "payment_mode" character varying, "smart_scales_enabled" boolean, "drive_thru_lanes" integer, "geofencing_enabled" boolean, "geofencing_radius" integer, "license_plate_recognition" boolean, "current_location" jsonb, "schedule" jsonb, "offline_mode_enabled" boolean, "seats_available" integer, "experience_duration" integer, "pre_booking_required" boolean, "tasting_menu_only" boolean, "special_instructions" text, "experience_highlights" text, "config_metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3cb12980fcd3de774b4b4d4458f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tips" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "restaurant_id" uuid NOT NULL, "staff_id" uuid, "order_id" uuid, "amount" numeric(10,2) NOT NULL, "tip_type" character varying NOT NULL DEFAULT 'direct', "status" character varying NOT NULL DEFAULT 'pending', "distributed_at" TIMESTAMP, "distribution_details" jsonb, "message" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b63a628fdfd7517d8e58fe39199" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "restaurant_id" uuid NOT NULL, "order_id" uuid, "rating" integer NOT NULL, "food_rating" integer, "service_rating" integer, "ambiance_rating" integer, "value_rating" integer, "comment" text, "images" text, "sentiment" character varying, "sentiment_analysis" jsonb, "is_verified" boolean NOT NULL DEFAULT false, "is_visible" boolean NOT NULL DEFAULT true, "helpful_count" integer NOT NULL DEFAULT '0', "owner_response" character varying, "owner_responded_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_methods_method_type_enum" AS ENUM('credit_card', 'debit_card', 'pix', 'cash', 'voucher', 'wallet')`);
        await queryRunner.query(`CREATE TABLE "payment_methods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "method_type" "public"."payment_methods_method_type_enum" NOT NULL, "card_last_four" character varying, "card_brand" character varying, "card_exp_month" character varying, "card_exp_year" character varying, "pix_key" character varying, "external_payment_method_id" character varying, "is_default" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_34f9b8c6dfb4ac3559f7e2820d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "notification_type" character varying NOT NULL, "related_id" uuid, "related_type" character varying, "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "menu_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "restaurant_id" uuid NOT NULL, "name" character varying NOT NULL, "description" text, "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "icon" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_124ae987900336f983881cb04e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "loyalty_programs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "restaurant_id" uuid NOT NULL, "points" integer NOT NULL DEFAULT '0', "total_visits" integer NOT NULL DEFAULT '0', "total_spent" numeric(10,2) NOT NULL DEFAULT '0', "tier" character varying NOT NULL DEFAULT 'bronze', "last_visit" date, "rewards_claimed" jsonb, "available_rewards" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9911f010986d7730cc744f91ff4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP COLUMN "date_of_birth"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "profiles_cpf_key"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP COLUMN "cpf"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "subtotal_amount"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "estimated_time"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "subtotal"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "customer_name"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "customer_phone"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "customer_email"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "permissions"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "subtotal" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "delivery_address" text`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "delivery_phone" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "estimated_ready_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "actual_ready_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "completed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "total_price" numeric(10,2) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."order_items_status_enum" AS ENUM('pending', 'preparing', 'ready', 'delivered', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "status" "public"."order_items_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "prepared_by" character varying`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "prepared_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "reservation_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "seating_preference" character varying`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "occasion" character varying`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "dietary_restrictions" text`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "contact_phone" character varying`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "contact_email" character varying`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "confirmed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "seated_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "completed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "cancelled_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "cancellation_reason" text`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "metadata" jsonb`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_transaction_type_enum" AS ENUM('recharge', 'payment', 'refund', 'withdrawal', 'tip_received', 'tip_distributed', 'salary')`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "transaction_type" "public"."wallet_transactions_transaction_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "balance_before" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "order_id" uuid`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "payment_method_id" uuid`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "external_transaction_id" character varying`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'confirmed', 'preparing', 'ready', 'delivering', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "tax_amount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "tip_amount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "discount_amount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menu_items" ALTER COLUMN "is_available" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menu_items" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menu_items" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."reservations_status_enum" AS ENUM('pending', 'confirmed', 'seated', 'completed', 'cancelled', 'no_show')`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "status" "public"."reservations_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "reservation_time"`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "reservation_time" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservations" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservations" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurants" ALTER COLUMN "rating" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurants" ALTER COLUMN "total_reviews" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurants" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurants" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurants" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "restaurant_id" SET NOT NULL`);

        // Migrate role column from varchar to enum
        await queryRunner.query(`CREATE TYPE "public"."user_roles_role_enum" AS ENUM('owner', 'manager', 'chef', 'waiter', 'barman', 'maitre')`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "role" TYPE "public"."user_roles_role_enum" USING ("role"::text::"public"."user_roles_role_enum")`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "role" SET NOT NULL`);

        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tables" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tables" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tables" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "wallets_user_id_key"`);

        // Migrate wallet_type column from varchar to enum
        await queryRunner.query(`CREATE TYPE "public"."wallets_wallet_type_enum" AS ENUM('client', 'restaurant', 'staff')`);
        // Map 'personal' to 'client' for existing records
        await queryRunner.query(`UPDATE "wallets" SET "wallet_type" = 'client' WHERE "wallet_type" = 'personal'`);
        // Remove default before type conversion
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "wallet_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "wallet_type" TYPE "public"."wallets_wallet_type_enum" USING (CASE WHEN "wallet_type" = 'personal' THEN 'client'::"public"."wallets_wallet_type_enum" ELSE "wallet_type"::text::"public"."wallets_wallet_type_enum" END)`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "wallet_type" SET NOT NULL`);

        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "balance" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurant_service_configs" ADD CONSTRAINT "FK_40de79554ce9094ea8a34fc61b0" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_85fdda5fcce2f397ef8f117a2c6" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_e462517174f561ece2916701c0a" FOREIGN KEY ("menu_item_id") REFERENCES "menu_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_items" ADD CONSTRAINT "FK_8d1ee4780bf64ae94cbf3e53705" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "FK_ee6b00404309108652a2307c66c" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "FK_4af5055a871c46d011345a255a6" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD CONSTRAINT "FK_efe4eead3adf44a4649a3353efc" FOREIGN KEY ("owner_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_44b696310215894b1e52ef1864c" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tips" ADD CONSTRAINT "FK_518660b2e93e2020b48c7b72300" FOREIGN KEY ("customer_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tips" ADD CONSTRAINT "FK_7e4d7eeeefe022989219785b508" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tips" ADD CONSTRAINT "FK_5adea20dea015449e7b74c04323" FOREIGN KEY ("staff_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_2269110d10df8d494b99e1381d2" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tables" ADD CONSTRAINT "FK_77e362d578933cf4518770d11ae" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_c57d19129968160f4db28fc8b28" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_927b4a573ad974c8b9121a52d5e" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_methods" ADD CONSTRAINT "FK_d7d7fb15569674aaadcfbc0428c" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_categories" ADD CONSTRAINT "FK_a1650861201d802c0ad078fff8e" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_programs" ADD CONSTRAINT "FK_49b5b8923a593ecd9acc47f9cb8" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_programs" ADD CONSTRAINT "FK_7ba94e3fd6b70f24899bfdf34de" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "loyalty_programs" DROP CONSTRAINT "FK_7ba94e3fd6b70f24899bfdf34de"`);
        await queryRunner.query(`ALTER TABLE "loyalty_programs" DROP CONSTRAINT "FK_49b5b8923a593ecd9acc47f9cb8"`);
        await queryRunner.query(`ALTER TABLE "menu_categories" DROP CONSTRAINT "FK_a1650861201d802c0ad078fff8e"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "payment_methods" DROP CONSTRAINT "FK_d7d7fb15569674aaadcfbc0428c"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_927b4a573ad974c8b9121a52d5e"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_c57d19129968160f4db28fc8b28"`);
        await queryRunner.query(`ALTER TABLE "tables" DROP CONSTRAINT "FK_77e362d578933cf4518770d11ae"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_2269110d10df8d494b99e1381d2"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "tips" DROP CONSTRAINT "FK_5adea20dea015449e7b74c04323"`);
        await queryRunner.query(`ALTER TABLE "tips" DROP CONSTRAINT "FK_7e4d7eeeefe022989219785b508"`);
        await queryRunner.query(`ALTER TABLE "tips" DROP CONSTRAINT "FK_518660b2e93e2020b48c7b72300"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_44b696310215894b1e52ef1864c"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "restaurants" DROP CONSTRAINT "FK_efe4eead3adf44a4649a3353efc"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "FK_4af5055a871c46d011345a255a6"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "FK_ee6b00404309108652a2307c66c"`);
        await queryRunner.query(`ALTER TABLE "menu_items" DROP CONSTRAINT "FK_8d1ee4780bf64ae94cbf3e53705"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_e462517174f561ece2916701c0a"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_85fdda5fcce2f397ef8f117a2c6"`);
        await queryRunner.query(`ALTER TABLE "restaurant_service_configs" DROP CONSTRAINT "FK_40de79554ce9094ea8a34fc61b0"`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "balance" DROP NOT NULL`);

        // Revert wallet_type column from enum back to varchar
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "wallet_type" DROP NOT NULL`);
        await queryRunner.query(`UPDATE "wallets" SET "wallet_type" = 'personal' WHERE "wallet_type" = 'client'`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "wallet_type" TYPE character varying USING ("wallet_type"::text)`);
        await queryRunner.query(`DROP TYPE "public"."wallets_wallet_type_enum"`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "wallet_type" SET DEFAULT 'personal'`);

        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "wallets_user_id_key" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "wallets" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "tables" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tables" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tables" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "is_active" DROP NOT NULL`);

        // Revert role column from enum back to varchar
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "role" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "role" TYPE character varying USING ("role"::text)`);
        await queryRunner.query(`DROP TYPE "public"."user_roles_role_enum"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "role" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "restaurant_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurants" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurants" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurants" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurants" ALTER COLUMN "total_reviews" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurants" ALTER COLUMN "rating" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservations" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservations" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "reservation_time"`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "reservation_time" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."reservations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "status" character varying DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "menu_items" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menu_items" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menu_items" ALTER COLUMN "is_available" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "discount_amount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "tip_amount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "tax_amount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "status" character varying DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "external_transaction_id"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "payment_method_id"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "order_id"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "balance_before"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP COLUMN "transaction_type"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_transaction_type_enum"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "cancellation_reason"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "cancelled_at"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "completed_at"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "seated_at"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "confirmed_at"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "contact_email"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "contact_phone"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "dietary_restrictions"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "occasion"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "seating_preference"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP COLUMN "reservation_date"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "prepared_at"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "prepared_by"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."order_items_status_enum"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "total_price"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "completed_at"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "actual_ready_at"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "estimated_ready_at"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "delivery_phone"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "delivery_address"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "subtotal"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "permissions" jsonb`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "customer_email" character varying`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "customer_phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD "customer_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "subtotal" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "estimated_time" integer`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "subtotal_amount" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD "cpf" character varying`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "profiles_cpf_key" UNIQUE ("cpf")`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD "date_of_birth" date`);
        await queryRunner.query(`DROP TABLE "loyalty_programs"`);
        await queryRunner.query(`DROP TABLE "menu_categories"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "payment_methods"`);
        await queryRunner.query(`DROP TYPE "public"."payment_methods_method_type_enum"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "tips"`);
        await queryRunner.query(`DROP TABLE "restaurant_service_configs"`);
        await queryRunner.query(`DROP TYPE "public"."restaurant_service_configs_service_type_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_restaurant_id" ON "user_roles" ("restaurant_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_user_id" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reservations_time" ON "reservations" ("reservation_time") `);
        await queryRunner.query(`CREATE INDEX "idx_reservations_restaurant_id" ON "reservations" ("restaurant_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reservations_user_id" ON "reservations" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_menu_items_restaurant_id" ON "menu_items" ("restaurant_id") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_status" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_restaurant_id" ON "orders" ("restaurant_id") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_user_id" ON "orders" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "fk_wallets_user" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "fk_wallets_restaurant" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "fk_wallet_transactions_wallet" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tables" ADD CONSTRAINT "fk_tables_restaurant" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_user" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurants" ADD CONSTRAINT "fk_restaurants_owner" FOREIGN KEY ("owner_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "fk_reservations_user" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "fk_reservations_restaurant" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "fk_reservations_table" FOREIGN KEY ("table_id") REFERENCES "tables"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_items" ADD CONSTRAINT "fk_menu_items_restaurant" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_items_order" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_items_menu_item" FOREIGN KEY ("menu_item_id") REFERENCES "menu_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_user" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_restaurant" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_table" FOREIGN KEY ("table_id") REFERENCES "tables"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
