import { RecipeDifficulty } from './entities/drink-recipe.entity';

/**
 * Seed data for the 5 default drink recipes.
 * These are global recipes (restaurant_id = null) available to all restaurants.
 */
export const DRINK_RECIPES_SEED = [
  {
    name: 'Gin Tonica Aurora',
    category: 'Gin',
    description:
      'Um gin tonico refrescante com notas florais de hibisco e lavanda, decorado com framboesa e limao.',
    difficulty: RecipeDifficulty.EASY,
    preparation_time_minutes: 5,
    glass_type: 'Highball',
    garnish: 'Pepino + Cardamomo',
    base_spirit: 'Gin',
    serving_temp: 'gelado',
    ingredients: [
      { name: 'Gin Artesanal', amount: '60', unit: 'ml' },
      { name: 'Tonica Premium', amount: '120', unit: 'ml' },
      { name: 'Pepino', amount: '2', unit: 'fatias' },
      { name: 'Cardamomo', amount: '3', unit: 'sementes' },
    ],
    steps: [
      'Encha a taca balloon com gelo ate a borda.',
      'Despeje o gin artesanal sobre o gelo.',
      'Adicione as fatias de pepino e as sementes de cardamomo.',
      'Complete com tonica premium gelada, vertendo devagar pela lateral.',
      'Mexa suavemente uma unica vez e sirva imediatamente.',
    ],
    tags: ['refreshing', 'floral', 'citrus'],
    price: 38.0,
    image_url: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400',
  },
  {
    name: 'Negroni Classico',
    category: 'Gin',
    description:
      'O classico italiano equilibrado entre amargo, doce e herbal. Perfeito como aperitivo.',
    difficulty: RecipeDifficulty.EASY,
    preparation_time_minutes: 3,
    glass_type: 'Rocks',
    garnish: 'Twist de laranja',
    base_spirit: 'Gin',
    serving_temp: 'temperatura ambiente',
    ingredients: [
      { name: 'Gin', amount: '30', unit: 'ml' },
      { name: 'Campari', amount: '30', unit: 'ml' },
      { name: 'Vermute Rosso', amount: '30', unit: 'ml' },
    ],
    steps: [
      'Adicione gelo ao mixing glass.',
      'Despeje gin, Campari e vermute rosso em partes iguais.',
      'Mexa suavemente por 20 segundos ate a bebida resfriar.',
      'Coe para o copo old fashioned com pedra de gelo grande.',
      'Decore com twist de laranja flamejado.',
    ],
    tags: ['bitter', 'classic', 'aperitivo'],
    price: 42.0,
    image_url: 'https://images.unsplash.com/photo-1551751299-1b51cab2694c?w=400',
  },
  {
    name: 'Espresso Martini',
    category: 'Vodka',
    description:
      'Coquetel elegante que combina a intensidade do cafe com a suavidade da vodka. Ideal para apos o jantar.',
    difficulty: RecipeDifficulty.MEDIUM,
    preparation_time_minutes: 5,
    glass_type: 'Martini',
    garnish: '3 graos de cafe',
    base_spirit: 'Vodka',
    serving_temp: 'gelado',
    ingredients: [
      { name: 'Vodka', amount: '45', unit: 'ml' },
      { name: 'Licor de Cafe (Kahlua)', amount: '30', unit: 'ml' },
      { name: 'Espresso', amount: '30', unit: 'ml' },
      { name: 'Xarope simples', amount: '5', unit: 'ml' },
    ],
    steps: [
      'Prepare o espresso e deixe resfriar levemente.',
      'Adicione todos os ingredientes a coqueteleira com gelo.',
      'Shake vigoroso por 15 segundos para criar espuma.',
      'Coe duplo para a taca martini previamente gelada.',
      'Decore com 3 graos de cafe sobre a espuma.',
    ],
    tags: ['coffee', 'elegant', 'after-dinner'],
    price: 40.0,
    image_url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400',
  },
  {
    name: 'Caipirinha Premium',
    category: 'Rum',
    description:
      'A caipirinha elevada com cachaca envelhecida e acucar demerara. Sabor brasileiro autenticado.',
    difficulty: RecipeDifficulty.EASY,
    preparation_time_minutes: 5,
    glass_type: 'Rocks',
    garnish: 'Limao',
    base_spirit: 'Cachaca',
    serving_temp: 'gelado',
    ingredients: [
      { name: 'Cachaca Envelhecida', amount: '60', unit: 'ml' },
      { name: 'Limao taiti', amount: '1', unit: 'unidade' },
      { name: 'Acucar demerara', amount: '2', unit: 'colheres de cha' },
    ],
    steps: [
      'Corte o limao em 4 partes e retire o miolo branco.',
      'Macere o limao com o acucar demerara no fundo do copo.',
      'Adicione gelo picado ate encher o copo.',
      'Despeje a cachaca envelhecida.',
      'Mexa bem e sirva imediatamente.',
    ],
    tags: ['brazilian', 'citrus', 'refreshing'],
    price: 32.0,
    image_url: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=400',
  },
  {
    name: 'Moscow Mule',
    category: 'Vodka',
    description:
      'Refrescante e picante, servido na iconica caneca de cobre. Perfeito para dias quentes.',
    difficulty: RecipeDifficulty.EASY,
    preparation_time_minutes: 3,
    glass_type: 'Copper Mug',
    garnish: 'Fatia de limao + Hortela',
    base_spirit: 'Vodka',
    serving_temp: 'gelado',
    ingredients: [
      { name: 'Vodka', amount: '45', unit: 'ml' },
      { name: 'Ginger Beer', amount: '120', unit: 'ml' },
      { name: 'Suco de limao fresco', amount: '15', unit: 'ml' },
      { name: 'Hortela', amount: '4', unit: 'folhas' },
    ],
    steps: [
      'Encha a caneca de cobre com gelo ate a borda.',
      'Adicione o suco de limao fresco.',
      'Despeje a vodka sobre o gelo.',
      'Complete com ginger beer gelada.',
      'Decore com fatia de limao e folhas de hortela.',
    ],
    tags: ['refreshing', 'spicy', 'citrus'],
    price: 36.0,
    image_url: 'https://images.unsplash.com/photo-1556855810-ac404aa91e85?w=400',
  },
];
